import norx/typ

type
  orxPLUGIN_FUNCTION_BASE_ID_RENDER* {.size: sizeof(cint).} = enum
    orxPLUGIN_FUNCTION_BASE_ID_RENDER_INIT = 0,
    orxPLUGIN_FUNCTION_BASE_ID_RENDER_EXIT,
    orxPLUGIN_FUNCTION_BASE_ID_RENDER_GET_WORLD_POSITION,
    orxPLUGIN_FUNCTION_BASE_ID_RENDER_GET_SCREEN_POSITION,
    orxPLUGIN_FUNCTION_BASE_ID_RENDER_NUMBER,
    orxPLUGIN_FUNCTION_BASE_ID_RENDER_NONE = orxENUM_NONE
