#!/bin/bash
# Generates color vectors from orxColorList.inc to be inserted into vector.nim

INPUT_COLOR_LIST="$ORX/include/display/orxColorList.inc"
OUTPUT_COLOR_LIST="../src/norx/colorList.nim"

echo "input: $INPUT_COLOR_LIST"

if [[ ! -f "$INPUT_COLOR_LIST" ]]; then
   echo "Error: ORX header file $INPUT_COLOR_LIST not found. Env variable ORX not set?" >&2
   exit 1
fi

echo >$OUTPUT_COLOR_LIST "# DON'T EDIT - Generated by scripts/createNimColors.sh"
echo >>$OUTPUT_COLOR_LIST "import lib, vectorType"
grep 'orxCOLOR_DECLARE(' "$INPUT_COLOR_LIST" | awk '{ print $1 }' | awk 'BEGIN{ FS="("} {print $2}' | awk 'BEGIN { FS=","} { print $1}' | awk '{ print "var orxVECTOR_"$0"* {.importc: \"orxVECTOR_"$0"\", dynlib: libORX.}: orxVECTOR" }' >>$OUTPUT_COLOR_LIST

echo "generated: $OUTPUT_COLOR_LIST"

